---
title: "LUAD_pt_smi.R"
author: "Chua Damien"
output: github_document
---

## Loading data
```{r}
LCO <- readRDS("./Data/LCO.RDS")

```



## Data Preprocessing
```{r}
plot1 <- VlnPlot(LCO, features = "nCount_Nanostring", pt.size = 0.1) + NoLegend()
plot2 <- ImageFeaturePlot(LCO, features = "nCount_Nanostring") + theme(legend.position = "right")
wrap_plots(plot1, plot2)

LCO <- SCTransform(LCO, assay = "Nanostring", verbose = FALSE)
plot2 <- ImageFeaturePlot(LCO, features = "nCount_SCT") + theme(legend.position = "right")
wrap_plots(plot1, plot2)


LCO <- RunPCA(LCO, assay = "SCT", verbose = FALSE, npcs=50)
ElbowPlot(LCO, reduction = "pca")
LCO <- RunUMAP(LCO, reduction = "pca", dims = 1:10)
LCO <- FindNeighbors(LCO, reduction = "pca", dims = 1:10)
LCO <- FindClusters(LCO, verbose = FALSE)


```

## Cell annotation
```{r}

Idents(LCO1) <-  LCO1$seurat_clusters
LCO1 <- RenameIdents(object = LCO1, 
                    `7` = "adenocarcinoma",
                    `9` = "B_cell",
                    `8` = "B_cell",
                    `5` = "B_cell",
                    `4` = "B_cell",
                    `11` = "mast_cell",
                    `10` = "T_cell",
                    `3` = "macrophages",
                    `6` = "endothelial",
                    `0` = "fibroblast",
                    `12` = "fibroblast"
                    )  
LCO1$cell_type <- Idents(LCO1)



## Imageplot
ImageDimPlot(LCO1, dark.background = F, border.color = "black", axes=T,
             cols= c("adenocarcinoma" = "black",
                     "B_cell" = "#800000",
                     "mast_cell" = "green",
                     "T_cell" = "blue",
                     "macrophages" = "orange",
                     "endothelial" = "magenta",
                     "fibroblast" = "yellow"
                     )) + theme_bw()

## Umap plot
DimPlot(LCO1, reduction = "umap", label = F,
        cols= c("adenocarcinoma" = "black",
                "B_cell" = "#800000",
                "mast_cell" = "green",
                "T_cell" = "blue",
                "macrophages" = "orange",
                "endothelial" = "magenta",
                "fibroblast" = "yellow" )) + theme_bw()

## Dotplot
DotPlot(LCO1, features = c("SERPINA1", "S100A2", "ITGA3","SAT1", "KRT7","KRT8", "KRT18","KRT19", "S100A6",  #Adenocarcinoma
                          "TPSAB1/B2", "CPA3", "KIT", "IL1RL1",#mast cell
                          "NEAT1", "MALAT1", #T cells
                          "IGHG1", "IGHG2","IGKC", "IGHA1", "MHC I",# Bcells
                          "CD14", "CD74", "CD68", "HLA-DRB","C1QB","LYZ", "CTSD", #macrophages
                          "SPARCL1", "IGFBP7", "RGS5", "PECAM1", "HSPG2", "CD93", "COL4A1", "COL18A1", "APP", "FLT1", # Endothelial
                          "COL1A1", "COL3A1", "COL1A2", "COL6A3", "MMP2", "BGN", #Fibro1
                          "LUM", "RPL21","RPL37", "MGP", "RACK1", "TIMP1" ),
        cols = c("blue","red")) + #fibro2
  RotatedAxis()

```

## Plot summary
```{r}

## Stacked Bar plot 
library(dittoSeq)

dittoBarPlot(object = LCO1, var = "cell_type",
  group.by = "orig.ident",
  color.panel= c("adenocarcinoma" = "black",
          "B_cell" = "#800000",
          "mast_cell" = "green",
          "T_cell" = "blue",
          "macrophages" = "orange",
          "endothelial" = "magenta",
          "fibroblast" = "yellow" )
  ) + theme_bw()

```

## Colocalization Plots
```{r}

# fibroblast, adeno
ImageDimPlot(LCO1, dark.background = F, border.color = "black", axes=T,
             cols= c("adenocarcinoma" = "black",
                     "B_cell" = "lightgrey",
                     "mast_cell" = "lightgrey",
                     "T_cell" = "lightgrey",
                     "macrophages" = "lightgrey",
                     "endothelial" = "lightgrey",
                     "fibroblast" = "yellow"
             )) + theme_bw()

# endo, adeno
ImageDimPlot(LCO1, dark.background = F, border.color = "black", axes=T,
             cols= c("adenocarcinoma" = "black",
                     "B_cell" = "lightgrey",
                     "mast_cell" = "lightgrey",
                     "T_cell" = "lightgrey",
                     "macrophages" = "lightgrey",
                     "endothelial" = "magenta",
                     "fibroblast" = "lightgrey"
             )) + theme_bw()


#### Ratio of fibroblast and endo against adeno
table(LCO1$cell_type)

df<- data.frame(cell_type = factor(c("fibroblast", "endothelial_cells"), levels = c("fibroblast", "endothelial_cells")),
                ratio = c(ratio_fibro, ratio_endo)) 

ggplot(df, aes(x=cell_type, y=ratio, fill = cell_type)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=c("fibroblast" = "yellow", 
                             "endothelial_cells" ="magenta")) + 
  theme_bw() + scale_x_discrete(guide = guide_axis(angle = 45))
```

## Colocolization analysis
```{r}

library(CellChat)
data.input = Seurat::GetAssayData(LCO1, layer = "data", assay = "SCT") # normalized data matrix
meta = data.frame(labels = Seurat::Idents(LCO1), samples = "sample1", row.names = names(Seurat::Idents(LCO1))) meta$samples <- factor(meta$samples)

spatial.locs = Seurat::GetTissueCoordinates(LCO1, scale = NULL, cols = c("imagerow", "imagecol")) 
rownames(spatial.locs) <-spatial.locs$cell
spatial.locs<- spatial.locs[,1:2]

conversion.factor = 0.18
d = computeCellDistance(spatial.locs)
spot.size = min(d)*conversion.factor # converting the distance in Pixels to Micrometers
spatial.factors = data.frame(ratio = conversion.factor, tol = spot.size/2)

d.spatial <- computeCellDistance(coordinates = spatial.locs, ratio = spatial.factors$ratio, tol = spatial.factors$tol)
min(d.spatial[d.spatial!=0]) 

cellchat <- createCellChat(object = data.input, meta = meta, group.by = "labels",
                           datatype = "spatial", coordinates = spatial.locs, spatial.factors = spatial.factors)

CellChatDB <- CellChatDB.human
showDatabaseCategory(CellChatDB)

CellChatDB.use <- subsetDB(CellChatDB, search = c("Secreted Signaling", "ECM-Receptor", "Cell-Cell Contact"), key = "annotation") # use Secreted Signaling
cellchat@DB <- CellChatDB.use

dplyr::glimpse(CellChatDB$interaction)

cellchat <- subsetData(cellchat) 
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat, variable.both = F)

cellchat <- computeCommunProb(cellchat, type = "truncatedMean", trim = 0.1,
                              distance.use = TRUE, interaction.range = 250, scale.distance = 2.5,
                              contact.dependent = TRUE, contact.range = 100)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)


par(mfrow = c(1,2), xpd=TRUE)
netVisual_heatmap(cellchat, measure = "count", 
                  color.use = c("adenocarcinoma" = "black",
                                "B_cell" = "#800000",
                                "mast_cell" = "green",
                                "T_cell" = "blue",
                                "macrophages" = "orange",
                                "endothelial" = "magenta",
                                "fibroblast" = "yellow" ),
                  color.heatmap = "Reds")

netVisual_heatmap(cellchat, measure = "weight", color.heatmap = "Reds")


CellChatDB <- CellChatDB.human
cellchat@DB <- CellChatDB.human

netVisual_bubble(cellchat, sources.use = c("fibroblast", "adenocarcinoma"), 
                 targets.use = c("fibroblast", "adenocarcinoma"), 
                 angle.x = 45, remove.isolate = T)

netVisual_bubble(cellchat, sources.use = c("endothelial", "adenocarcinoma"), 
                 targets.use = c("endothelial", "adenocarcinoma"), 
                 angle.x = 45, remove.isolate = T)



```

